name: "Lint"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '44 13 * * 1'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: "Navigate to frontend directory"
        run: cd frontend

      - name: "Install dependencies"
        run: "npm ci"
        working-directory: ./frontend

      - name: "Run ESLint"
        run: "npm run lint"
        working-directory: ./frontend

      - name: "Run Prettier"
        run: "npm run format"
        working-directory: ./frontend